
import "@/src/assets/globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";


import DashboardLayout from "@/src/components/layout/DashboardLayout";
import { Inter } from 'next/font/google'
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: "Dashboard - Inicio",
    description: "Generated by create next app",
};

export default async function PropsLayout({ children }: { children: React.ReactNode }) {
    return (
                <DashboardLayout>
                    <Suspense fallback={<Loading />}>
                        {children}
                    </Suspense>
                </DashboardLayout>
    );
}
