import { Toaster } from "react-hot-toast";
import "@/src/assets/globals.css";
import DashboardLayout from "@/src/components/DashboardLayout";
import { Inter } from 'next/font/google'
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Dashboard - Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
