import { Toaster } from "react-hot-toast";
import "@/src/assets/globals.css";
import React from "react";
import ChildrenProps from "@/@types/children";

export const metadata = {
  title: "HomePage - ZapStream  ",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: ChildrenProps) {
  return (
    <React.Fragment>  
      {children}
    </React.Fragment>
  );
}
